import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const merriWeather = localFont({
  src: [
    {
      path: "./fonts/MerriweatherSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/MerriweatherSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/MerriweatherSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-poppins",
});

export const metadata = {
  title: "NachoFace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${merriWeather.variable} antialiased`}>{children}</body>
    </html>
  );
}
